---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hydra-maester.fullname" . }}-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hydra-maester.labels" . | nindent 4 }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if not .Values.singleNamespaceMode }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hydra-maester.fullname" . }}-role
rules:
 - apiGroups:
   - hydra.ory.sh
   resources:
   - oauth2clients
   - oauth2clients/status
   verbs:
   - get
   - list
   - watch
   - create
   - update
   - patch
   - delete
 - apiGroups:
   - ""
   resources:
   - secrets
   verbs:
   - list
   - watch
   - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hydra-maester.fullname" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "hydra-maester.fullname" . }}-account # Service account assigned to the controller pod.
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hydra-maester.fullname" . }}-role
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hydra-maester.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
 - apiGroups:
   - ""
   resources:
   - secrets
   verbs:
   - get
   - list
   - watch
   - create
 - apiGroups:
   - hydra.ory.sh
   resources:
   - oauth2clients
   - oauth2clients/status
   verbs:
   - get
   - list
   - watch
   - create
   - update
   - patch
   - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hydra-maester.fullname" . }}-role-binding
  namespace:  {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hydra-maester.fullname" . }}-account # Service account assigned to the controller pod.
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hydra-maester.fullname" . }}-role

{{- $name := include "hydra-maester.fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- range .Values.enabledNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}-role
  namespace: {{ . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-role-binding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}-account # Service account assigned to the controller pod.
    namespace:  {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}-role
{{- end }}
